### ISSUE TITLE
Add Firebase logo

### ISSUE THREAD

**Issue by mgibas** [jarjarapps/dev-stickers.logo#139]
- [x] Verify license at https://www.firebase.com/
- [x] Create PNG

**Comment by mgibas** [comment]
https://creativecommons.org/licenses/by/3.0/

source: https://firebase.google.com/terms/

**Comment by justjavac** [comment]
> Except as otherwise noted, **the content of this page** is licensed under the Creative Commons Attribution 3.0 License, and **code samples** are licensed under the Apache 2.0 License.

I do not think it(logo) is licensed under the CC BY 3.0 License.
